import assert from 'node:assert/strict';
import { join } from 'node:path';

export async function verifyUsage(page, name, root) {
  await page.getByRole('tab', { name: 'Usage', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#usage-content .usage-model'));
  await page.getByText('Usage by task', { exact: true }).click();
  assert.match(await page.locator('.usage-stages').filter({ has: page.getByText('Usage by task', { exact: true }) }).innerText(), /Head assignments/);
  assert.match(await page.locator('.usage-stages').filter({ has: page.getByText('Usage by task', { exact: true }) }).innerText(), /uncached input/);
  assert.ok(await page.locator('.usage-provider').count() > 0);
  assert.match(await page.locator('.usage-providers').innerText(), /reasoning: (high|xhigh|medium|ultra)/);
  assert.match(await page.locator('.usage-providers').innerText(), /Uncached input/);
  assert.match(await page.locator('.usage-providers').innerText(), /Input cache hit/);
  await page.getByText('Usage by request', { exact: true }).click();
  await page.getByText('Usage by participant', { exact: true }).click();
  assert.match(await page.locator('.usage-repeat').innerText(), /Each attempt counts once/);
  await page.waitForFunction(() => document.querySelector('#account-usage').textContent.includes('account-wide'));
  assert.match(await page.locator('#account-usage').innerText(), /Open Claude account usage/);
  for (const label of ['Consultants', 'Review rounds', 'Correction orders', 'Research calls', 'Web actions']) assert.ok((await page.locator('.usage-activity').innerText()).includes(label));
  const current = await page.locator('.usage-total').innerText();
  assert.notEqual(current, 'Unavailable');
  assert.ok(Number(current.replace(/\D/gu, '')) > 0);
  assert.match(await page.locator('#usage-content').innerText(), /gpt-6-(sol|astra)/);
  assert.match(await page.locator('#usage-content').innerText(), /before tracking was added/);
  assert.equal(await page.locator('#thread').isVisible(), false);
  await page.locator('#usage-scope').selectOption('all');
  await page.waitForFunction(() => document.querySelector('#usage-status').textContent.startsWith('Usage updates'));
  const total = Number((await page.locator('.usage-total').innerText()).replace(/\D/gu, ''));
  assert.ok(total >= Number(current.replace(/\D/gu, '')));
  await page.locator('.usage-model summary').first().click();
  assert.match(await page.locator('.usage-model details[open]').first().innerText(), /Reasoning output/);
  await page.locator('#toast').waitFor({ state: 'hidden' });
  await page.evaluate(() => { document.activeElement?.blur(); window.scrollTo(0, 0); });
  await page.screenshot({ path: join(root, 'output', 'playwright', `${name}-usage-desktop.png`), fullPage: true });
  await page.setViewportSize({ width: 320, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Usage reflows at 320px');
  assert.equal(await page.locator('#consultation-view').isVisible(), true, 'Mobile view picker is available');
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: join(root, 'output', 'playwright', `${name}-usage-mobile.png`), fullPage: true });
  await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight));
  const picker = await page.locator('#consultation-view').boundingBox();
  assert.ok(picker && picker.y >= 76 && picker.y + picker.height <= 844, 'Mobile view picker remains visible while scrolling');
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight));
  assert.ok((await page.getByRole('tab', { name: 'Usage', exact: true }).boundingBox()).y >= 82);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.getByRole('tab', { name: 'Usage', exact: true }).focus();
  await page.keyboard.press('ArrowLeft');
  assert.equal(await page.getByRole('tab', { name: 'Sources', exact: true }).getAttribute('aria-selected'), 'true');
  await page.keyboard.press('ArrowRight');
  await page.route('**/api/usage*', route => route.fulfill({ status: 503, json: { error: 'synthetic_usage_failure' } }));
  await page.locator('#usage-refresh').click();
  await page.waitForFunction(() => document.querySelector('#usage-status').textContent.includes('could not refresh'));
  await page.unroute('**/api/usage*');
  await page.locator('#usage-refresh').click();
  await page.waitForFunction(() => document.querySelector('#usage-status').textContent.startsWith('Usage updates'));
  await page.reload();
  await page.locator('#usage').waitFor({ state: 'visible' });
  await page.waitForFunction(() => document.querySelector('#usage-content .usage-model'));
  await page.locator('.usage-calls summary').click();
  assert.match(await page.locator('.usage-calls').innerText(), /Attempts include retries/);
  const timelineFilter = page.getByRole('combobox', { name: 'Filter timeline by request' });
  await timelineFilter.selectOption({ index: 1 });
  assert.ok(await page.locator('.usage-calls article:visible').count() > 0);
  const selected = await timelineFilter.inputValue();
  assert.ok(await page.locator('.usage-calls article:visible').evaluateAll((articles, key) => articles.every(article => article.dataset.requestKey === key), selected));
  await timelineFilter.selectOption('all');
  const usageResponse = await page.request.get(new URL('/api/usage', page.url()).href);
  const payload = await usageResponse.json();
  const sample = payload.usage ?? payload;
  sample.callDetails[0].usageSource = 'upstream_responses'; sample.callDetails[0].responseCount = 2;
  sample.incomplete = 1; sample.unavailable = 1;
  sample.models[0].tokens.input.unavailable = 1;
  sample.repeatWork = { ...sample.repeatWork, attempts: 0, total: null, coverage: 'partial', attributionIncomplete: true };
  sample.callDetails.push({id:'synthetic-unreported',model:'gpt-6-sol',provider:'codex',stage:'specialist_reply',status:'cancelled',startedAt:new Date().toISOString(),finishedAt:new Date().toISOString(),usage:[]});
  await page.route('**/api/account-usage', route => route.fulfill({status:200,json:{accounts:{codex:{status:'available',checkedAt:new Date().toISOString(),windows:[{bucket:'codex',kind:'primary',usedPercent:32,windowDurationMins:300,resetsAt:1790456400}]},claude_code:{status:'external',windows:[]}}}}));
  await page.route('**/api/usage*', route => route.fulfill({status:200,json:payload}));
  await page.locator('#usage-refresh').click();
  await page.waitForFunction(() => document.querySelector('#usage-content').textContent.includes('Partial reported tokens'));
  assert.match(await page.locator('#usage-content').innerText(), /partial/);
  assert.match(await page.locator('.usage-repeat').innerText(), /Unavailable tokens · 0 attempts · partial/);
  assert.match(await page.locator('.usage-repeat').innerText(), /zero repeat work cannot be established/);
  await page.waitForFunction(() => document.querySelector('#account-usage').textContent.includes('32% used'));
  assert.equal(await page.locator('#account-usage meter').getAttribute('value'), '32');
  await page.locator('.usage-calls summary').click();
  assert.match(await page.locator('.usage-calls').innerText(), /Accounting: upstream response fields/);
  assert.match(await page.locator('.usage-calls').innerText(), /Usage unavailable — this does not mean zero tokens/);
  await page.setViewportSize({width:320,height:844});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true,'All attempts reflow at 320px');
  await page.unroute('**/api/usage*');
  await page.unroute('**/api/account-usage');
  await page.setViewportSize({width:1280,height:900});
  await page.getByRole('tab', { name: 'Discussion', exact: true }).click();
}
